sonar.projectKey=ios-app
sonar.projectName=iOS App
sonar.sources=arcana-ios/Sources
sonar.tests=arcana-iosTests
sonar.swift.file.suffixes=.swift
sonar.exclusions=**/arcana.xcodeproj/**,**/*.xcassets/**,**/DerivedData/**,**/build/**
sonar.coverage.exclusions=**/Mocks/**,**/*Mock*.swift,**/*Stub*.swift
sonar.scm.disabled=true
